export const TOPICS = [
  {
    title: "Plano Cartesiano",
    definition: "Sistema formado por dos rectas perpendiculares que permiten ubicar puntos mediante coordenadas.",
    explanation: "El eje X mide la posición horizontal y el eje Y mide la posición vertical. El cruce de ambos es el origen (0, 0).",
    example: "El punto (4, 3) está 4 unidades a la derecha y 3 unidades arriba del origen.",
    commonError: "Intercambiar el orden de las coordenadas: primero va X y después Y.",
    tip: "Lee cada punto como un recorrido: primero camina en horizontal y luego en vertical.",
  },
  {
    title: "Par Ordenado",
    definition: "Expresión de la forma (x, y) que indica la posición exacta de un punto.",
    explanation: "La primera coordenada siempre corresponde al eje X; la segunda corresponde al eje Y.",
    example: "(−2, 5) significa 2 unidades a la izquierda y 5 unidades hacia arriba.",
    commonError: "Pensar que (2, −5) y (−5, 2) representan el mismo lugar.",
    tip: "El orden importa: un par ordenado cambia si se intercambian sus valores.",
  },
  {
    title: "Ejes Coordenados",
    definition: "Rectas numéricas que dividen el plano en cuatro regiones.",
    explanation: "El eje X es horizontal; el eje Y es vertical. Ambos permiten medir distancias desde el origen.",
    example: "Los puntos sobre el eje X tienen y = 0; los puntos sobre el eje Y tienen x = 0.",
    commonError: "Confundir un punto del eje con un punto del cuadrante.",
    tip: "Si una coordenada es cero, el punto está sobre un eje.",
  },
  {
    title: "Cuadrantes",
    definition: "Cuatro regiones del plano determinadas por los signos de x e y.",
    explanation: "I: (+,+), II: (−,+), III: (−,−), IV: (+,−).",
    example: "El punto (−3, 4) está en el cuadrante II.",
    commonError: "Asignar cuadrantes sin revisar ambos signos.",
    tip: "Memoriza el recorrido contrario a las manecillas del reloj: I, II, III, IV.",
  },
  {
    title: "Distancia entre dos puntos",
    definition: "Medida del segmento que une dos puntos del plano.",
    explanation: "Se calcula con la fórmula d = √((x₂−x₁)² + (y₂−y₁)²).",
    example: "Entre (1, 2) y (4, 6): d = √(3² + 4²) = 5.",
    commonError: "No elevar al cuadrado las diferencias antes de sumarlas.",
    tip: "La fórmula nace del teorema de Pitágoras aplicado al plano.",
  },
  {
    title: "Punto medio",
    definition: "Punto que queda exactamente a la mitad del segmento entre dos puntos.",
    explanation: "Se obtiene promediando las coordenadas: M = ((x₁+x₂)/2, (y₁+y₂)/2).",
    example: "Entre (−2, 4) y (6, 8): M = (2, 6).",
    commonError: "Promediar solo una coordenada o sumar sin dividir entre dos.",
    tip: "Si el punto medio está bien, su distancia a ambos extremos es igual.",
  },
  {
    title: "Simetría",
    definition: "Transformación que refleja un punto respecto a un eje o al origen.",
    explanation: "Respecto a X cambia el signo de y; respecto a Y cambia el signo de x; respecto al origen cambian ambos.",
    example: "El punto (3, −5) reflejado en el eje Y es (−3, −5).",
    commonError: "Cambiar el signo de la coordenada equivocada.",
    tip: "Piensa en un espejo: el eje que usas como espejo no cambia.",
  },
  {
    title: "Intervalos",
    definition: "Conjunto de números comprendidos entre dos extremos.",
    explanation: "Los corchetes [ ] incluyen el extremo; los paréntesis ( ) lo excluyen.",
    example: "[−1, 4) incluye −1, todos los valores intermedios y excluye 4.",
    commonError: "Dibujar igual un extremo abierto y uno cerrado.",
    tip: "Punto lleno significa incluido; punto vacío significa excluido.",
  },
  {
    title: "Operaciones entre conjuntos",
    definition: "Procedimientos para combinar conjuntos y obtener nuevas regiones.",
    explanation: "La unión junta, la intersección conserva lo común, la diferencia elimina y el complemento toma lo que falta en el universo.",
    example: "Si A=[0,5] y B=[3,8], entonces A∩B=[3,5].",
    commonError: "Confundir unión con intersección cuando los intervalos se superponen.",
    tip: "Antes de operar, marca visualmente cada conjunto; la región resultado se vuelve evidente.",
  },
];

export const EXAMPLES = [
  { expression: "A∪B", label: "Unión básica", note: "Combina todo lo que pertenece a A o a B." },
  { expression: "A∩B", label: "Intersección", note: "Muestra solamente la parte común." },
  { expression: "A−B", label: "Diferencia", note: "Quita de A la región que coincide con B." },
  { expression: "A△B", label: "Diferencia simétrica", note: "Conserva las partes no compartidas." },
  { expression: "(A∪B)−C", label: "Expresión combinada", note: "Primero une A y B, luego elimina C." },
  { expression: "((A∩B)−C)'", label: "Con complemento", note: "Opera dentro del paréntesis y toma lo restante del universo." },
  { expression: "A∪(B△C)", label: "Con paréntesis internos", note: "Resuelve B△C antes de unir con A." },
];
